# Generated by Django 4.2.4 on 2023-08-22 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('raspi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('blink_count', models.IntegerField()),
                ('blink_length', models.IntegerField()),
                ('exec_time', models.TimeField()),
                ('year', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('day', models.IntegerField(blank=True, null=True)),
                ('weekday', models.CharField(blank=True, max_length=10, null=True)),
                ('job_id', models.CharField(max_length=100)),
                ('repetition', models.CharField(choices=[('JO', 'Just Once'), ('ED', 'Daily'), ('EW', 'Weekly'), ('EM', 'Monthly'), ('EY', 'Yearly')], max_length=10)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raspi.node')),
            ],
        ),
    ]
