# Generated by Django 4.2.4 on 2023-08-24 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raspi', '0001_initial'),
        ('commandpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionalTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blink_count', models.IntegerField()),
                ('blink_length', models.IntegerField()),
                ('value1', models.DecimalField(decimal_places=2, max_digits=8)),
                ('value2', models.DecimalField(decimal_places=2, max_digits=8)),
                ('condition', models.CharField(choices=[('LT', 'Less Than'), ('GT', 'Greater Than'), ('BT', 'Between')], max_length=10)),
                ('actuator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actuator_node', to='raspi.node')),
                ('sensor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_node', to='raspi.node')),
            ],
        ),
    ]
