# Generated by Django 4.2.4 on 2023-08-24 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandpage', '0003_alter_conditionaltask_sensor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditionaltask',
            name='value2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
