# Generated by Django 4.2.4 on 2023-08-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('macaddress', models.CharField(max_length=30, unique=True)),
                ('room', models.IntegerField()),
                ('type', models.CharField(choices=[('AC', 'Actuator'), ('SE', 'Sensor')], max_length=10)),
                ('sensor_type', models.CharField(blank=True, max_length=20, null=True)),
                ('last_connection', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
