# Generated by Django 4.2.3 on 2023-08-25 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raspi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='last_connection',
        ),
    ]
