# Generated by Django 4.2.3 on 2023-08-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raspi', '0002_remove_node_last_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='connected',
            field=models.BooleanField(default=False),
        ),
    ]
